name: test2
on:
  workflow_dispatch:
jobs:
  test_suite: # Name of the job
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.9.1' # In command line run ‚Äúnode -v‚Äù and choose your version
      - run: npm ci
#      - run: npm config set script-shell "C:\Program Files\Git\bin\bash.exe"
      - name: run test2
        run: npm run test2 # Our name of the headless script
      - name: Copy History
        if: always()
        run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
      - name: Generate Report
        if: always()
        run: npm run allure:generate # Name of the allure generate script
      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report
      - name: Deploy üöÄ copy of rep
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: main # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
          target-folder: docs
          force: false
      - name: Deploy üöÄ
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
          force: false
